Training_seting:
    training_epoch: 200
    batch_size: 128
    num_workers: 4
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 5.e-4
    model_width: 0.15
    dataset_path: traffic_light_data
    weight_path: Weights/
    